-- OPTIONAL: Advanced Looker Studio Views
-- =====================================================
-- NOTE: These are optional advanced views for Looker Studio.
-- Your basic migration already created the main views you need:
--   • all_historical_bills
--   • all_historical_categories
-- 
-- You can use those views directly in Looker Studio.
-- 
-- This file contains more sophisticated views for advanced analytics,
-- but they reference column names that may not exist in your data.
-- Only run these if you need advanced dashboards.
-- =====================================================

-- To use these views, you would need to:
-- 1. Update the column names to match your actual data schema
-- 2. Replace {project_id} with: guttmacher-legislative-tracker  
-- 3. Replace {dataset_id} with: legislative_tracker_historical
-- 4. Test each view individually

-- For now, stick with the working views created by migration_pipeline.py:
--   • all_historical_bills (394 bills across 2002-2004)
--   • all_historical_categories (127 categories across 2002-2004)